
# LEDs
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

set_property PACKAGE_PIN J15 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property PACKAGE_PIN L16 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property PACKAGE_PIN M13 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property PACKAGE_PIN R15 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property PACKAGE_PIN R17 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[4]}]
set_property PACKAGE_PIN T18 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[5]}]
set_property PACKAGE_PIN U18 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[6]}]
set_property PACKAGE_PIN R13 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[7]}]
set_property PACKAGE_PIN T8 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[8]}]
set_property PACKAGE_PIN U8 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[9]}]
set_property PACKAGE_PIN R16 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[10]}]
set_property PACKAGE_PIN T13 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[11]}]
set_property PACKAGE_PIN H6 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[12]}]
set_property PACKAGE_PIN U12 [get_ports {SW[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[13]}]
set_property PACKAGE_PIN U11 [get_ports {SW[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[14]}]
set_property PACKAGE_PIN V10 [get_ports {SW[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[15]}]

# 8-Digit Seven-Segment Display Segments
set_property PACKAGE_PIN T10 [get_ports {disp_seg_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[0]}]
set_property PACKAGE_PIN R10 [get_ports {disp_seg_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[1]}]
set_property PACKAGE_PIN K16 [get_ports {disp_seg_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[2]}]
set_property PACKAGE_PIN K13 [get_ports {disp_seg_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[3]}]
set_property PACKAGE_PIN P15 [get_ports {disp_seg_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[4]}]
set_property PACKAGE_PIN T11 [get_ports {disp_seg_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[5]}]
set_property PACKAGE_PIN L18 [get_ports {disp_seg_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[6]}]
set_property PACKAGE_PIN H15 [get_ports {disp_seg_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[7]}]
# 8-Digit Seven-Segment Display Anodes, Active-Low
set_property PACKAGE_PIN J17 [get_ports {disp_an_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[0]}]
set_property PACKAGE_PIN J18 [get_ports {disp_an_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[1]}]
set_property PACKAGE_PIN T9 [get_ports {disp_an_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[2]}]
set_property PACKAGE_PIN J14 [get_ports {disp_an_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[3]}]
set_property PACKAGE_PIN P14 [get_ports {disp_an_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[4]}]
set_property PACKAGE_PIN T14 [get_ports {disp_an_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[5]}]
set_property PACKAGE_PIN K2 [get_ports {disp_an_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[6]}]
set_property PACKAGE_PIN U13 [get_ports {disp_an_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[7]}]

# System Clock, 100MHz
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# LD16 RGB LED Signals
set_property PACKAGE_PIN N15 [get_ports rgb1_red_o]
set_property IOSTANDARD LVCMOS33 [get_ports rgb1_red_o]
set_property PACKAGE_PIN M16 [get_ports rgb1_green_o]
set_property IOSTANDARD LVCMOS33 [get_ports rgb1_green_o]
set_property PACKAGE_PIN R12 [get_ports rgb1_blue_o]
set_property IOSTANDARD LVCMOS33 [get_ports rgb1_blue_o]
# LD17 RGB LED Signals
set_property PACKAGE_PIN N16 [get_ports rgb2_red_o]
set_property IOSTANDARD LVCMOS33 [get_ports rgb2_red_o]
set_property PACKAGE_PIN R11 [get_ports rgb2_green_o]
set_property IOSTANDARD LVCMOS33 [get_ports rgb2_green_o]
set_property PACKAGE_PIN G14 [get_ports rgb2_blue_o]
set_property IOSTANDARD LVCMOS33 [get_ports rgb2_blue_o]


set_property PACKAGE_PIN C17 [get_ports {keypad_x[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_x[3]}]
set_property PACKAGE_PIN D18 [get_ports {keypad_x[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_x[2]}]
set_property PACKAGE_PIN E18 [get_ports {keypad_x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_x[1]}]
set_property PACKAGE_PIN G17 [get_ports {keypad_x[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_x[0]}]

set_property PACKAGE_PIN D17 [get_ports {keypad_y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_y[3]}]
set_property PACKAGE_PIN E17 [get_ports {keypad_y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_y[2]}]
set_property PACKAGE_PIN F18 [get_ports {keypad_y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_y[1]}]
set_property PACKAGE_PIN G18 [get_ports {keypad_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_y[0]}]

set_property PACKAGE_PIN D14 [get_ports led_clk] #jb1
set_property IOSTANDARD LVCMOS33 [get_ports led_clk]
set_property PACKAGE_PIN F16 [get_ports led_cs] #jb2
set_property IOSTANDARD LVCMOS33 [get_ports led_cs]
set_property PACKAGE_PIN G16 [get_ports led_din] #jb3
set_property IOSTANDARD LVCMOS33 [get_ports led_din]
